name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Install ubuntu deps
      if: ${{ matrix.os.host }} == ubuntu-latest
      run: sudo apt-get install -y libudev-dev libhidapi-dev libusb-1.0-0-dev
      
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: annepro2tools
        path: ./target/release/annepro2_tools
