name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Install ubuntu deps
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install -y libudev-dev libhidapi-dev libusb-1.0-0-dev
      
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --verbose
    - uses: actions/upload-artifact@v3
      if: ${{ runner.os == 'Linux' }}
      name: Upload ubuntu builds
      with:
        name: annepro2tools-linux
        path: ./target/release/

    - uses: actions/upload-artifact@v3
      if: ${{ runner.os == 'Windows' }}
      name: Upload windows build
      with:
        name: annepro2tools-windows
        path: ./target/release/
