name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Install ubuntu deps
      if: ${{ runner.os == 'ubuntu-latest' }}
      run: sudo apt-get install -y libudev-dev libhidapi-dev libusb-1.0-0-dev
      
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --verbose
    - uses: actions/upload-artifact@v3
      with:
        if: ${{ matrix.os == 'ubuntu-latest' }}
        name: annepro2tools
        path: ./target/release/annepro2_tools

    - uses: actions/upload-artifact@v3
      with:
        if: ${{ runner.os == 'windows-latest' }}
        name: annepro2tools.exe
        path: ./target/release/annepro2_tools_x64.exe
